- CMakeLists.txt
- include/libndt/libndt.hpp
- libndt-client.cpp
- test/libndt_test.cpp
This change adds support for the Locate v2 API, and removes legacy logic for the deprecated mlab-ns. With these changes, the reference client is able to complete an ndt7 test targeting the M-lab platform using access tokens received from the Locate v2 API.
The client will unconditionally report the client_name, client_version, and client_application strings in the locate request which will be forwarded to the ndt7 server and archived with test data.
```
$ ./ndt7-cpp -download -upload
will run the download sub-test
will run the upload sub-test
will auto-select a suitable server
locate_api url: https://locate.measurementlab.net/v2/nearest/ndt/ndt7?client_application=m-lab/ndt7-client-cc&client_version=v0.1.0
starting ndt7 download test
[ 2%] speed:    428 Mbit/s
[ 4%] speed:    475 Mbit/s
[ …
```
> Add Locate v2 API support

- CMakeLists.txt
- README.md
- include/libndt/libndt.hpp
- libndt-client.cpp
This change adds new functionality to the library and libndt-client.
libndt-client:
* adds several new flags
* `-key` provides an optional API key for the Locate API
* `-hostname` is now explicit flag, required for static targets
*  `-scheme` defaults to "wss" and can be set to "ws".
* help text is significantly revised
libndt:
* wss scheme is the default
* complete support for static targets
* CLIENT_NAME can be set at build time
```sh
$ ./libndt-client -scheme ws -hostname=localhost -port 80 -upload
will run the upload sub-test
will use this hostname: localhost
will use this port: 80
will use this scheme: ws
will use this static NDT server: ws://localhost:80
ndt7: starting upload test: ws://localhost
[ 3%] speed:   20.6 Gbit/s
[ 5%] speed:     21 Gbit/s
[ 8%] speed:   21.1 Gbit/s
[10%] …
```
> Update libndt-client flags and support static targets

- .travis.yml
- Dockerfile
- docker.sh
- test/curlx_test.cpp
- test/libndt7_test.cpp
- test/sys_test.cpp
- third_party/github.com/catchorg/Catch2/catch.hpp
This change adds a Dockerfile used for development and testing based on configuration from https://github.com/measurement-kit/docker-ci-images/tree/master.
Because the base image and environment include various updates, we needed to update catch.hpp to the latest v2.* release which remains c++11 compatible (Oct 2022) - https://github.com/catchorg/Catch2/releases/tag/v2.13.10
As well, we update the travis environment from xenial (16.04) to jammy (22.04) to update docker engine to prevent a build failure related to earlier docker versions.
Part of:
* https://github.com/m-lab/ndt7-client-cc/issues/2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/9)
> Add Dockerfile for testing

- include/libndt7/libndt7.hpp
- ndt7-client-cc.cpp
This change correctly applies the locate-api-key (when given) to the `/v2/priority/*` resource. This change also adds a new flag to specify an alternate `-locate-api-url=`, which is helpful for testing.
Part of:
* https://github.com/m-lab/ndt7-client-cc/issues/2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/12)
> fix(locate): Add new flag -locate-api-url=

- AUTHORS
- LICENSE
@m-lab is stepping in and adopting https://github.com/measurement-kit/libndt into this repository.
As part of transferring ownership of libndt to @m-lab and specifically to @stephen-soltesz, we have agreed on a change of license from BSD three clause to Apache v2.0, given that Apache 2.0 is more in line with @m-lab policies.
Part of https://github.com/m-lab/ndt7-client-cc/issues/2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/13)
> chore: update LICENSE and AUTHORS

- README.md
This diff tweaks README.md to mention the exact commit we forked this client from measurement-kit/libndt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/16)
> doc(README): mention commit we forked from

- include/libndt7/preamble.hpp
- single_include/libndt7.hpp
This change fixes a typo remaining from the library renaming.
Fixes: https://github.com/m-lab/ndt7-client-cc/issues/20
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/22)
> fix(typo): remove double seven from library rename

- include/libndt7/libndt7.hpp
- ndt7-client-cc.cpp
- single_include/libndt7.hpp
This change updates the docstring for `run()` and updates the retry logic to retry all servers before failing. Previously both upload and download could fail but still return `true`, which was a mistake.
This change also removes other vestigial references to ndt5 and web100.
Fixes: https://github.com/m-lab/ndt7-client-cc/issues/19
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/24)
> fix: retry servers fully and update docstring for run

- include/libndt7/libndt7.hpp
- single_include/libndt7.hpp
This change adds `SummaryData` to the public interface of libndt7 library, with a function that can return a `SummaryData` instance after a successful `run()`.
Fixes: https://github.com/m-lab/ndt7-client-cc/issues/18
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/25)
> feat(summary): make SummaryData part of public interface

- CMakeLists.txt
- README.md
This change adds two simple install targets for the reference client and single include library. This change also updates the README with hints for specifying an alternate install prefix.
Previously, there were no install targets defined.
Fixes: https://github.com/m-lab/ndt7-client-cc/issues/17
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/26)
> feat(cmake): add install targets

- ndt7-client-cc.cpp
Previously, it was not possible to add additional Locate API parameters without code changes. This change adds a new flag `-locate-params` which accepts multiple `name=value` options separated with a comma. Each will be passed to the Locate API request.
Example:
```sh
./ndt7-client-cc -locate-params=region=US-CA -download
./ndt7-client-cc -locate-params=early_exit=250,region=US-NY -download
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/27)
> feat(flag): add -locate-params flag

- include/libndt7/libndt7.hpp
- single_include/libndt7.hpp
Previously, `Client::on_result` was called conditionally when `get_verbosity() == verbosity_debug` even though the default implementation used `LIBNDT_EMIT_INFO` to report information. Rather than depend on DEBUG log level to be called (which enables additional debug behavior), this change makes the call unconditional and updates the default implementation of `on_result` to use DEBUG logging. Derived classes may override this implementation for their own use.
Fixes: https://github.com/m-lab/ndt7-client-cc/issues/21
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/28)
> Use DEBUG logging by default for `Client::on_result`

- include/libndt7/libndt7.hpp
- single_include/libndt7.hpp
The unsupported fields are used for upload retransmission rate. Create a macro for these fields and define the macro to enable it when linux version >= 4.19.0.
Issue: https://github.com/m-lab/ndt7-client-cc/issues/32
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/36)
> Add a macro for unsupported fields in tcp_info

- test/libndt7_test.cpp
When building `libndt7_test.cpp.o` for ARM64, both `libndt7.hpp` and `catch.hpp` will use `<linux/types.h>`. We will get unknown type error for `__u64`, `__u32` and `__u8` if we don't include it first.
Issue: https://github.com/m-lab/ndt7-client-cc/issues/30
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/34)
> fix: unknown type error on ARM64

- include/libndt7/libndt7.hpp
- single_include/libndt7.hpp
Update to use `static_cast`.
Issue: https://github.com/m-lab/ndt7-client-cc/issues/31
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/35)
> fix: Implicit conversion error on ARM32

- .clang-format
According to Google style guide[1], update `ColumnLimit` to 80.
[1] https://google.github.io/styleguide/cppguide.html#Line_Length
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/37)
> Update clang config

- include/libndt7/internal/curlx.hpp
- include/libndt7/internal/err.hpp
- include/libndt7/internal/logger.hpp
- include/libndt7/internal/sys.hpp
- single_include/libndt7.hpp
Use clang-format to reformat the files under internal.
Run: `clang-format -i include/libndt7/internal/*`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/39)
> Reformat files under include/libndt7/internal

- include/libndt7/libndt7.hpp
- ndt7-client-cc.cpp
- single_include/libndt7.hpp
Since we plan to split a header for Client and use forward declaration, the json fields should be unique_ptr.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/41)
> Update json fields in Client to unique_ptr

- include/libndt7/internal/curlx.hpp
- include/libndt7/libndt7.hpp
- ndt7-client-cc.cpp
- single_include/libndt7.hpp
This change adds support for providing a user-agent string and propagating this string to the request to the Locate API. With this change, client installations may provide unique user agents identifiable to the Locate API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/42)
> Add user agent to Locate API requests

- include/libndt7/libndt7.cpp
- include/libndt7/libndt7.h
- single_include/libndt7.hpp
Update the argument name with clear unit.
* Rename `elapsed` to `elapsed_sec`.
* Rename `data` to `data_bytes`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt7-client-cc/43)
> Rename argument with unit suffix
